language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.5
env:
  - SOAP4R_PARSERS=oxparser
  - SOAP4R_PARSERS=nokogiriparser
  - SOAP4R_PARSERS=libxmlparser
  - SOAP4R_PARSERS=ogaparser
  - SOAP4R_PARSERS=rexmlparser

gemfile:
  - gemfiles/httpclient.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      env: SOAP4R_PARSERS=ogaparser

  allow_failures:
    - rvm: 1.8.7
      env: SOAP4R_PARSERS=oxparser
    - rvm: jruby
    - rvm: rbx
    - env: SOAP4R_PARSERS=libxmlparser
    - rvm: 2.2.5

notifications:
  recipients:
    - coder.notify@not404.com

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: ec0b3e0a786f4b93a2522db298c4155c77e25c2137592df0d4f9c2f1a491b89a
